# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.9'
# Define services
services:


  keycloak:
    container_name: keycloak-auth
    image: quay.io/keycloak/keycloak:latest
      #build:
      # context: .
    #args:
    # KEYCLOAK_VERSION: 22.0.1
    command:
      - "start-dev"
    ports:
      - "8180:8080"
    networks:
      - keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HEALTH_ENABLED: true
    depends_on:
      - keycloak-db
    #volumes:
    #  - /home/keycloak/automobile-realm.json:/opt/keycloak/data/import/automobile-realm.json
  # Database Service (Postgres) for Keycloak


  keycloak-db:
    image: postgres:15-alpine
    container_name: keycloak-db
    hostname: 'keycloak-db'
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_keycloak:/var/lib/postgresql/data
    environment:
      - TZ=GMT+7
      - PGTZ=GMT+7
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
    networks: [ keycloak ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U" ]
      timeout: 45s
      interval: 10s
      retries: 10

  express-api:
      build:
          context: ./generate-pdf-engine
          dockerfile: Dockerfile
      command: '/app/scripts/docker/local-run.sh'
      container_name: express-api
      ports:
          - '3000:3000'

  spring-api:
      build:
          context: ./doc-api
          dockerfile: Dockerfile
      container_name: doc-api
      ports:
          - "9091:9091"

  mysql:
      image: mysql:latest
      container_name: dev_mysql
      restart: always
      ports:
          # <Port exposed> : < MySQL Port running inside container>
          - "3306:3306"
      volumes:
          - ./data/db:/var/lib/mysql
      environment:
          MYSQL_DATABASE: "db"
          MYSQL_USER: "user"
          MYSQL_PASSWORD: "password"
          MYSQL_ROOT_PASSWORD: "root"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: "dev_phpmyadmin"
      restart: always
      ports:
          - 9090:80
      environment:
          PMA_HOST: mysql
          PMA_PORT: 3306


networks:
  keycloak:
    name: keycloak
    driver: bridge
  devkh_micro_net:
    external: true
    name: devkh_micro_net


volumes:
  keycloak_db_vol:
  keycloak_data:
  postgres_data_keycloak:
    driver: local
